### ISSUE TITLE
Thanks for the package!

### ISSUE THREAD

**Issue by JonasGeschke** [prioritizr/wdpar#18]
Hi, thank you very much for the package, very exciting!
I am indeed trying to dissolve the whole WDPA into a "flat layer of global protected areas" (terrestrial and coastal only, but thats not a problem).

I didnt get to install wdpar yet, due to some dependencie issues. I will try again on monday. Until then: Is it possible with your package to dissolve (get rid of overlapping areas) the whole database? How do you deal with processing performance capacities?
Would be great to have some discussion about this. I am also happy to provide my code, in case it helps developing the package.

Best regards,
Jonas

**Comment by jeffreyhanson** [comment]
Hi,

My pleasure - thanks for looking into it and reaching out! 

Yeah there were some dependency issues with wdpar this last week with the wdman and RSelenium packages being archived on CRAN, but now both of those are back on CRAN so hopefully it all works now. Please let me know if you run into any more installation issues?

No, this package isn't really going to work with the full WDPA. If you really, really, really wanted to, you could use the package to clean the data for each country separately in parallel - but you would need 100+ GB RAM, 20+ CPUs, and at least a couple of weeks for run time (or longer). For the global database, I would recommend trying out https://github.com/jeffreyhanson/global-protected-areas - but this uses ESRI ArcMap instead of R so it's not a FOSS solution. I'm sorry I don't have a more helpful answer.

Cheers,

Jeff

**Comment by JonasGeschke** [comment]
Hi, thanks for the quick response and your Arcmap resource!
I got wdpar installed now, no further problems coming up. I will test the dissolving/ erasing overlaps with a couple of countries and get back to you how it works as a loop with the global database.

Best greetings,
Jonas

**Comment by JonasGeschke** [comment]
So far it doesnt work at all, as I have an error coming up the CRS would be different throughout the loop. Which actually doesnt make sense to me, as all subsets come from the same WDPA object. However ...

Dealing with the WDPA in R seems to be sort of a bigger issue, so once again thanks for the package! In case you are interested in my contribution, feel free to drop me an email @ jonas.geschke@ips.unibe.ch 

Best regards, Jonas
