### ISSUE TITLE
wdpa_clean.R

### ISSUE THREAD

**Issue by fguilhaumon** [prioritizr/wdpar#26]
Hello,

working with wdpa_clean.R. Regarding the following step:

`## return empty dataset if no valid non-empty geometries remain`

I'm wondering if line 311:

`if (all(sf::st_is_empty(x))) {`

should be:

`if (any(sf::st_is_empty(x))) {`

so that the error exists if any geometry is empty. As for now it seems that all geometries need to be empty. Am I missing something ?

Cheers.

**Comment by jeffreyhanson** [comment]
Hi, 

Thanks for checking out the wdpar package. No, I think line 311 is correct (maybe the comment above it is a bit confusing). It's perfectly valid for `sf` objects to have empty geometries (indeed functions like `st_buffer` should still work), so an empty geometry is not an necceasrily an error. The reason why this code (line 311) checks for empty geometries is that some of the cleaning code later in the function assumes that there is at least one non-empty (per ``sf::st_is_empty`) and valid geometry (per `sf::st_is_valid`) in the `x` object. The subsequent code can handle a mix of empty and non-empty geometries (because the code constantly checks and removes for any empty geometries). So, this code (line 311) is used to detect when all of the geometries in the `sf` object are empty, so that the function can exit early and return an `sf` object that just contains an empty geometry (instead of throwing an error when the subsequent code encounters an `sf` object that just contains an empty geometry).

Does that make sense? If not, I can try and explain this more clearly?

**Comment by fguilhaumon** [comment]
Thanks for the follow up. Yes totally makes sense. The problem was on the side of my understanding of the scope of the functions.
