### ISSUE TITLE
It takes forever to eraseoverlap for global dataset.

### ISSUE THREAD

**Issue by sahmoli** [prioritizr/wdpar#43]
Could the code (especially the eraseoverlap part) be parrelelled in R?

**Comment by jeffreyhanson** [comment]
Hi @sahmoli,

Thanks for reaching out! 

Yeah, I don't recommend trying to use erase overlaps with the global datset unless you really need it (and don't mind waiting ages for it to complete). For example, if you plan on rasterizing the protected area data after cleaning it, then you don't need to worry about erasing the overlapping parts of protected areas. Additionally, if you want a vector layer showing protected area boundaries without any overlaps -- and don't need the attribute data for each protected area individually -- then you can (1) clean that data without the erase overlaps step, and (2) dissolve all the protected areas togeather (removing overlaps) using [`wdpa_dissolve()`](https://prioritizr.github.io/wdpar/reference/wdpa_dissolve.html). To achieve this, you can tell the  `wdpa_clean()` function to skip the erase overlaps step by setting `erase_overlaps = FALSE`. 

Also, regarding your question about paralellizing the code, I don't think it could be easily parallelized because the prcoedure for erasing overlaps is sequential. This is because the algorithm works by iteratively removing overlapping bits---so the part of a protected area that gets erased depends on what protected areas have previously been processed. For reference, the relevant code is here: https://github.com/prioritizr/wdpar/blob/master/R/st_erase_overlaps.R. If you can come up with a way of parallelizing this, I'd be happy to review a PR?

Does that help? Let me know if you have any further questions?

**Comment by sahmoli** [comment]
Thank you so much for the quick reply. 
I am doing a global analysis using wdpa. I need to calculate the cropland area within each PA, and analyze them with different attributes of PA. So that means I need the vector layer with attributes. 

I runned the code for global analysis several times. It works well in the begining, but it usually has some error after two or three weeks. It only occupied 11% of CPU and 16% of RAM, so I wonder whether there is a way to accelerate it.  

You are right, the procedure seems to be sequential.

**Comment by sahmoli** [comment]
Wow, super smart! Yes, I want to analyze the IUCN categories.

I will try this now, and let you know how it goes.

Thank you so much

**Comment by jeffreyhanson** [comment]
Excellent - great to hear we might have a solution! 

Yeah, please let me know if this doesn't work and we brainstorm some more on how to get this working?

I think I've answered all your qestions for now so, if you don't mind, could we please close this issue? I use open issues to keep track of which things on GitHub I need to respond to or focus on. Please feel free to re-open this issue, or open a new one, if you have any further questions?

**Comment by sahmoli** [comment]
Sounds great.

**Comment by jeffreyhanson** [comment]
Awesome - thanks!

**Comment by sahmoli** [comment]
After I do the wdpa_dissolve for one type of IUCN category, I found that I lost the attribte table for each PA. The attribute table of the multipolygon after dissolving has only one row.

**Comment by jeffreyhanson** [comment]
Yeah, that's what I would expect. If we dissolve an sf object, then this is spatially merging all the the data togeather (effectively the same as `sf::st_union()` by with extra stuff to help avoid geometry issues). So, we subset the global PA data to extract IUCN category `"Ia"` protected areas, and then dissolve that subset, we should a new sf object with a single row that has the spatial boundaries for all category `"Ia" protected areas (with no overlaps between them). If I understand correctly, this isn't an issue though, because you're only interested in IUCN categories and not other attributes? Or maybe I'm misunderstanding something?

**Comment by sahmoli** [comment]
Yeah, you are right. I will let it you know how it goes. 
You could close it now. I guess the whole process needs hours.

**Comment by jeffreyhanson** [comment]
Ah ok - sounds good - thanks!

**Comment by sahmoli** [comment]
I realized that this method might have potential problems.  In one of the following analyses, I need the variables of the status_yr and GIS_area of the PA, which are not available following the current method. 
If I want to keep multiple attributes of each PA after erase overlap of global PA dataset., are there any other solutions?,

**Comment by jeffreyhanson** [comment]
Hmm, if you want to keep track of the (i) year each PA was established and (ii) IUCN category of each PA, you could split the full dataset into multiple subsets based on different combinations of `STATUS_YR` and `IUCN_CAT` and then apply the procedure we talked about previously to dissolve and then recombine the data. Since each combination of `STATUS_YR`/`IUCN_CAT` is processed seperately, it might be possible to speed this up using parallel processing. 

I can't think of a way to retain the `GIS_AREA` of each protected area though. Since you want to account for the overlapping bits of protected areas, maybe it would be better to manually calculate the total area of each protected area after the removing the overlaps (e.g. using `sf::st_area()`)? Otherwise, if you use the `GIS_AREA` column, then that will not match the updated spatial extent of each PA after removing overlaps.

Also, since you're looking at overlap with agricultural areas, may I ask what data/resolution you're using for the agricultural areas? E.g., if the agricultural data are in raster format, then maybe there could be some way to rasterize the WDPA data at some stage in the analysis to reduce computational burden?

**Comment by sahmoli** [comment]
You are right, I do not need the GIS_AREA which could be calculated later. I plan to rasterize the layer after erase overlap.

After I filter the global PA dataset with  GIS_AREA > 1km2 and STATUS_YR between a range, there are only 85836 obs left.  It already runs for a whole day and it seems that it will finish in 2 days.

I will try the STATUS_YR/IUCN_CAT combination in parrellel in another PC, to see how long it will take.
I will let you know, how it goes.

Thank you so much.

**Comment by jeffreyhanson** [comment]
No worries! Oh I see. Yeah, if you plan on rasterizing the WDPA data, then I don't think you need to worry about erasing overlaps? This is because the rasterization process (e.g. if using ArcGIS, `raster::rasterize()`, `terra::rasterize()`, `fasterize::fasterize()`) will assign values to the output raster based on whether or not the geometries overlap with raster cell (unless you want to rasterize a specific field in the WDPA layer specifically, or compute percent coverage of each raster cell)?

**Comment by sahmoli** [comment]
Yes, I want to rasterize the STATUS_YR, so I need to erase overlap before rasterize. right?

**Comment by jeffreyhanson** [comment]
Hmm, just to check, do you want (i) a single-layer raster where each grid cell contains a value with STATUS_YR value, or (ii) a multi-layer raster (one layer for each STATUS_YR) indicating whether a PA as established within the grid cell in that year (i.e. grid cell values contain 0s and 1s)?

**Comment by sahmoli** [comment]
I just sent you an email ( ***@***.*** ), could we have
a voice chat on this?

**Comment by sahmoli** [comment]
> 

I think I want a single-layer raster where each grid cell contains a value with STATUS_YR value

**Comment by jeffreyhanson** [comment]
Sorry - I've been stuck in a meeting for the last while. Yeah, I can chat tomorrow - I'll respond to your email.

**Comment by jeffreyhanson** [comment]
Ah - yeah if you want a single-layer raster with grid cells containing STATUS_YR - then that makes things a lot easier. In cases where you have multiple protected areas overlapping with a single grid cell, how should this be handled? E.g., would you want the minimum value (corresponding to earliest established protected area in the grid cell) or the maximum value (corresponding to the most recently established protected area in the grid cell)?

**Comment by jeffreyhanson** [comment]
I would suggest using fasterize to rasterize the STATUS_YR values (https://www.rdocumentation.org/packages/fasterize/versions/1.0.3/topics/fasterize). If that doesn't work, then maybe try gdal_rasterize (https://www.rdocumentation.org/packages/gdalUtils/versions/2.0.3.2/topics/gdal_rasterize) (I find this works well for very large datasets).

**Comment by jeffreyhanson** [comment]
I think we resolved this issue, so I'll close this now - but please feel free to reopen it if you have any further questions.
