### ISSUE TITLE
JOSS Review: Add statement about state of the field 

### ISSUE THREAD

**Issue by Jo-Schie** [prioritizr/wdpar#62]
Last issue from my side. [JOSS Review criteria ask i](https://github.com/openjournals/joss-reviews/issues/4594)f the author describes the _"State of the field: Do the authors describe how this software compares to other commonly-used packages?"_

I guess that the `wdpar` package is pretty unique in the sense that there is no other R (or Python) package AFAIK that do exactly the same or something very similar to what you do. So it could be informative to the reader to write a short sentence in your manuscript that tells them that probably this is the only piece of software to deal with this very specific issue. I always enjoy if an R-package also lists alternatives s that could serve me and how they are different... so knowing that basically at the moment there is no alternative to the `wdpar` package could be a shortcut for some readers to not investigate too much into finding other alternatives (I guess there is also no other software outside the Python / R world to do so.) + it increases the value of your package to the reader in the sense that it is unique in what it does. 

Nevertheless, there is e.g. the Digital Observatory for Protected Areas [(DOPA)](https://dopa.jrc.ec.europa.eu/dopa/) which provides country summary stats on protected area progress towards AICHI. You could cite them because probably they have to apply exactly the same methods as you do and do allow you to create summary stats to a limited degree.

**Comment by jeffreyhanson** [comment]
Yeah, there are a few software packages that have been developed to help work with Protected Planet data. So, I've added a new paragraph to the manuscript with a brief overview of them (copied in below, and [see here for PDF](https://github.com/prioritizr/wdpar/blob/joschie-review/paper/paper.pdf)). Although DOPA have published paper documenting their methods for working with Protected Planet data (see [here](https://scholarworks.umass.edu/cgi/viewcontent.cgi?article=1017&context=foss4g)), I am unable to find any code online for these methods - so I don't think it's apropriate to include a comparison to their work because they haven't produced a software package. Is this OK?

---

> The \texttt{wdpar} \texttt{R} package provides superior functionality for processing Protected Planet data compared with other software packages. Although the \texttt{rwdpa} \texttt{R} package, \texttt{worldpa} \texttt{R} package, and the \texttt{pywdpa} \texttt{Python} package provide interfaces for downloading data from Protected Planet [r23; r24; r25], none of these software packages provide functionality for data cleaning. Additionally, the \texttt{rwdpa} \texttt{R} package has been archived. A command line tool was also developed to download and clean Protected Planet data [r26]. However, because the command line tool was implemented as a collection of \texttt{Python} scripts and configuration files, it is difficult to install and customize.

**Comment by Jo-Schie** [comment]
Looks fine to me.

**Comment by jeffreyhanson** [comment]
Brilliant - thank you!
